/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Health */
        get: operations["provider_health_api_providers_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Scene */
        post: operations["import_scene_api_scenes_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/import/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Scenario Yaml */
        post: operations["import_scenario_yaml_api_scenarios_import_yaml_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/orbit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario Orbit */
        get: operations["get_scenario_orbit_api_scenarios__scenario_id__orbit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control Scenario */
        post: operations["control_scenario_api_scenarios__scenario_id__control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Missions */
        get: operations["list_missions_api_missions_get"];
        put?: never;
        /** Create Mission */
        post: operations["create_mission_api_missions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Mission */
        post: operations["advance_mission_api_missions__mission_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Mission */
        post: operations["cancel_mission_api_missions__mission_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mission */
        get: operations["get_mission_api_missions__mission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/nodes/{node}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Snapshot */
        get: operations["get_node_snapshot_api_missions__mission_id__nodes__node__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/nodes/{node}/artifacts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Artifact */
        get: operations["get_node_artifact_api_missions__mission_id__nodes__node__artifacts__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mission Result */
        get: operations["get_mission_result_api_missions__mission_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Faults */
        get: operations["list_faults_api_scenarios__scenario_id__faults_get"];
        put?: never;
        /** Add Fault */
        post: operations["add_fault_api_scenarios__scenario_id__faults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/faults/{fault_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fault */
        delete: operations["delete_fault_api_scenarios__scenario_id__faults__fault_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transfers */
        get: operations["list_transfers_api_transfers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/protocol/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Protocol Transactions */
        get: operations["list_protocol_transactions_api_missions__mission_id__protocol_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protocol/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Protocol Transaction */
        get: operations["get_protocol_transaction_api_protocol_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protocol/transactions/{transaction_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Protocol Frames */
        get: operations["get_protocol_frames_api_protocol_transactions__transaction_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protocol/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Protocol */
        get: operations["stream_protocol_api_protocol_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product Manifest */
        get: operations["get_product_manifest_api_products__product_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIMode
         * @enum {string}
         */
        AIMode: "yolo" | "llm";
        /** Body_import_scenario_yaml_api_scenarios_import_yaml_post */
        Body_import_scenario_yaml_api_scenarios_import_yaml_post: {
            /** File */
            file: string;
        };
        /** Body_import_scene_api_scenes_import_post */
        Body_import_scene_api_scenes_import_post: {
            /** File */
            file: string;
        };
        /**
         * ClockAction
         * @enum {string}
         */
        ClockAction: "start" | "pause" | "resume" | "step" | "reset" | "set_rate";
        /** ContactWindow */
        ContactWindow: {
            /**
             * Aos
             * Format: date-time
             */
            aos: string;
            /**
             * Los
             * Format: date-time
             */
            los: string;
            /**
             * Max Elevation At
             * Format: date-time
             */
            max_elevation_at: string;
            /** Max Elevation Deg */
            max_elevation_deg: number;
        };
        /**
         * ExecutionState
         * @enum {string}
         */
        ExecutionState: "waiting" | "running" | "blocked" | "retryable_error" | "completed" | "cancelled";
        /** FaultRule */
        FaultRule: {
            /** Id */
            id?: string;
            link: components["schemas"]["LinkKind"];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Drop Rate
             * @default 0
             */
            drop_rate: number;
            /**
             * Corrupt Rate
             * @default 0
             */
            corrupt_rate: number;
            /**
             * Duplicate Rate
             * @default 0
             */
            duplicate_rate: number;
            /**
             * Reorder
             * @default false
             */
            reorder: boolean;
            /**
             * Disconnected
             * @default false
             */
            disconnected: boolean;
            /**
             * Extra Latency Ms
             * @default 0
             */
            extra_latency_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinkKind
         * @enum {string}
         */
        LinkKind: "gtx" | "uplink" | "downlink";
        /** LinkProfile */
        LinkProfile: {
            kind: components["schemas"]["LinkKind"];
            /** Bandwidth Bps */
            bandwidth_bps: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Jitter Ms
             * @default 0
             */
            jitter_ms: number;
            /**
             * Frame Payload Bytes
             * @default 65536
             */
            frame_payload_bytes: number;
            /**
             * Queue Capacity Bytes
             * @default 268435456
             */
            queue_capacity_bytes: number;
            /**
             * Max Retries
             * @default 5
             */
            max_retries: number;
        };
        /** MissionAdvance */
        MissionAdvance: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Playback Speed
             * @default 1
             * @enum {integer}
             */
            playback_speed: 1 | 2 | 5;
        };
        /** MissionCommand */
        MissionCommand: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Name
             * @default 北京目标光学观测
             */
            name: string;
            /**
             * Target Name
             * @default 北京演示目标
             */
            target_name: string;
            /**
             * Target Latitude
             * @default 39.9042
             */
            target_latitude: number;
            /**
             * Target Longitude
             * @default 116.4074
             */
            target_longitude: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at?: string;
            /**
             * Scene Id
             * @default demo-optical-scene
             */
            scene_id: string;
            /**
             * Enable Ai
             * @default true
             */
            enable_ai: boolean;
            /** @default yolo */
            ai_mode: components["schemas"]["AIMode"];
            /**
             * Project Context
             * @default SpaceZenith-Sim 光学观测任务
             */
            project_context: string;
            /**
             * Analysis Prompt
             * @default 识别图像中的主要地物、目标和异常，说明判断依据与不确定性。
             */
            analysis_prompt: string;
            scenario_snapshot?: components["schemas"]["ScenarioConfig"] | null;
            planned_windows?: components["schemas"]["PlannedWindows"] | null;
        };
        /** MissionCreate */
        MissionCreate: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Name
             * @default 北京目标光学观测
             */
            name: string;
            /**
             * Target Name
             * @default 北京演示目标
             */
            target_name: string;
            /**
             * Target Latitude
             * @default 39.9042
             */
            target_latitude: number;
            /**
             * Target Longitude
             * @default 116.4074
             */
            target_longitude: number;
            /**
             * Scene Id
             * @default demo-optical-scene
             */
            scene_id: string;
            /**
             * Enable Ai
             * @default true
             */
            enable_ai: boolean;
            /** @default yolo */
            ai_mode: components["schemas"]["AIMode"];
            /**
             * Project Context
             * @default SpaceZenith-Sim 光学观测任务
             */
            project_context: string;
            /**
             * Analysis Prompt
             * @default 识别图像中的主要地物、目标和异常，说明判断依据与不确定性。
             */
            analysis_prompt: string;
        };
        /** MissionDetail */
        MissionDetail: {
            command: components["schemas"]["MissionCommand"];
            status: components["schemas"]["MissionStatus"];
            /** Error */
            error?: string | null;
            phase: components["schemas"]["MissionPhase"];
            execution_state: components["schemas"]["ExecutionState"];
            /** Active Substage */
            active_substage?: string | null;
            ai_mode: components["schemas"]["AIMode"];
            planned_windows?: components["schemas"]["PlannedWindows"] | null;
            /** Block Reason */
            block_reason?: string | null;
            /**
             * Legacy Terminal
             * @default false
             */
            legacy_terminal: boolean;
            /** Next Action */
            next_action?: string | null;
            /**
             * Can Advance
             * @default false
             */
            can_advance: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Events */
            events?: components["schemas"]["TelemetryEvent"][];
            /** Products */
            products?: components["schemas"]["ProductManifest"][];
            /** Onboard Products */
            onboard_products?: components["schemas"]["ProductManifest"][];
            /** Transfers */
            transfers?: components["schemas"]["TransferRecord"][];
            /** Step Attempts */
            step_attempts?: components["schemas"]["MissionStepAttempt"][];
        };
        /**
         * MissionPhase
         * @enum {string}
         */
        MissionPhase: "initialized" | "uplink_complete" | "capture_complete" | "processing_complete" | "gtx_complete" | "ai_complete" | "completed";
        /**
         * MissionStatus
         * @enum {string}
         */
        MissionStatus: "planned" | "uplinking" | "maneuvering" | "capturing" | "l0_processing" | "l1a_processing" | "l1b_processing" | "gtx_transfer" | "ai_processing" | "ai_skipped" | "downlinking" | "completed" | "failed" | "cancelled";
        /** MissionStepAttempt */
        MissionStepAttempt: {
            /** Id */
            id?: string;
            /** Mission Id */
            mission_id: string;
            from_phase: components["schemas"]["MissionPhase"];
            target_phase: components["schemas"]["MissionPhase"];
            /** Attempt Number */
            attempt_number: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** @default running */
            state: components["schemas"]["ExecutionState"];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** MissionSummary */
        MissionSummary: {
            command: components["schemas"]["MissionCommand"];
            status: components["schemas"]["MissionStatus"];
            /** Error */
            error?: string | null;
            phase: components["schemas"]["MissionPhase"];
            execution_state: components["schemas"]["ExecutionState"];
            /** Active Substage */
            active_substage?: string | null;
            ai_mode: components["schemas"]["AIMode"];
            planned_windows?: components["schemas"]["PlannedWindows"] | null;
            /** Block Reason */
            block_reason?: string | null;
            /**
             * Legacy Terminal
             * @default false
             */
            legacy_terminal: boolean;
            /** Next Action */
            next_action?: string | null;
            /**
             * Can Advance
             * @default false
             */
            can_advance: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** NodeArtifact */
        NodeArtifact: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Observation Only
             * @default true
             */
            observation_only: boolean;
            /**
             * Previewable
             * @default false
             */
            previewable: boolean;
        };
        /**
         * NodeKind
         * @enum {string}
         */
        NodeKind: "ground" | "platform" | "optical" | "gpu";
        /** NodeSnapshot */
        NodeSnapshot: {
            node: components["schemas"]["NodeKind"];
            /** Mission Id */
            mission_id: string;
            /**
             * Reachable
             * @default true
             */
            reachable: boolean;
            /** Status */
            status: string;
            /** Observation Notice */
            observation_notice?: string | null;
            /** State */
            state?: {
                [key: string]: unknown;
            };
            /** Artifacts */
            artifacts?: components["schemas"]["NodeArtifact"][];
        };
        /** PlannedWindows */
        PlannedWindows: {
            uplink: components["schemas"]["ContactWindow"];
            capture: components["schemas"]["ContactWindow"];
            downlink: components["schemas"]["ContactWindow"];
            /** Target Name */
            target_name: string;
            /** Target Latitude */
            target_latitude: number;
            /** Target Longitude */
            target_longitude: number;
            /** Tle Line1 */
            tle_line1: string;
            /** Tle Line2 */
            tle_line2: string;
            /**
             * Minimum Elevation Deg
             * @default 5
             */
            minimum_elevation_deg: number;
        };
        /**
         * ProductLevel
         * @enum {string}
         */
        ProductLevel: "raw" | "l0" | "l1a" | "l1b" | "aux_context" | "thumbnail" | "stac" | "ai_result" | "result_package";
        /** ProductManifest */
        ProductManifest: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Mission Id */
            mission_id: string;
            level: components["schemas"]["ProductLevel"];
            /** Name */
            name: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Processing Parameters */
            processing_parameters?: {
                [key: string]: unknown;
            };
            /** Quality */
            quality?: {
                [key: string]: unknown;
            };
            /** Lineage */
            lineage?: string[];
            /** Artifact Path */
            artifact_path?: string | null;
        };
        /** ProtocolFrameTrace */
        ProtocolFrameTrace: {
            /** Id */
            id?: string;
            /** Transaction Id */
            transaction_id: string;
            /** Sequence */
            sequence: number;
            /** Total */
            total: number;
            /** Message Type */
            message_type: string;
            /** Payload Bytes */
            payload_bytes: number;
            /**
             * Simulated At
             * Format: date-time
             */
            simulated_at: string;
            /** Crc32C */
            crc32c?: string | null;
            /**
             * Crc Valid
             * @default true
             */
            crc_valid: boolean;
            /**
             * Attempt
             * @default 0
             */
            attempt: number;
            /**
             * Ack Status
             * @default sent
             * @enum {string}
             */
            ack_status: "sent" | "ack" | "nak" | "dropped" | "crc_error";
            /** Missing Sequences */
            missing_sequences?: number[];
        };
        /**
         * ProtocolLinkKind
         * @enum {string}
         */
        ProtocolLinkKind: "uplink" | "downlink" | "gtx" | "payload_bus";
        /** ProtocolPayloadView */
        ProtocolPayloadView: {
            /**
             * Kind
             * @default none
             * @enum {string}
             */
            kind: "json" | "binary" | "none";
            /** Mime Type */
            mime_type?: string | null;
            /** Decoded Json */
            decoded_json?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
        };
        /** ProtocolTransaction */
        ProtocolTransaction: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Mission Id */
            mission_id: string;
            link: components["schemas"]["ProtocolLinkKind"];
            /**
             * Protocol
             * @default SIMF/1
             */
            protocol: string;
            /** Message Type */
            message_type: string;
            source_node: components["schemas"]["NodeKind"];
            target_node: components["schemas"]["NodeKind"];
            /** Direction */
            direction: string;
            /** @default running */
            status: components["schemas"]["ProtocolTransactionStatus"];
            /**
             * Total Bytes
             * @default 0
             */
            total_bytes: number;
            /**
             * Frame Count
             * @default 0
             */
            frame_count: number;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Crc Failures
             * @default 0
             */
            crc_failures: number;
            /** Sha256 */
            sha256?: string | null;
            payload?: components["schemas"]["ProtocolPayloadView"];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Legacy Summary Only
             * @default false
             */
            legacy_summary_only: boolean;
        };
        /**
         * ProtocolTransactionStatus
         * @enum {string}
         */
        ProtocolTransactionStatus: "running" | "completed" | "failed";
        /** ScenarioConfig */
        ScenarioConfig: {
            /** Id */
            id?: string;
            /**
             * Name
             * @default 北京光学任务演示
             */
            name: string;
            /**
             * Seed
             * @default 20260811
             */
            seed: number;
            /**
             * Epoch
             * Format: date-time
             */
            epoch?: string;
            /**
             * Clock Rate
             * @default 10
             * @enum {integer}
             */
            clock_rate: 1 | 10 | 100;
            /**
             * Tle Line1
             * @default 1 55244U 23006C   26126.66766851  .00004587  00000-0  24048-3 0  9998
             */
            tle_line1: string;
            /**
             * Tle Line2
             * @default 2 55244  43.1978 352.6432 0015896 112.1710 248.0829 15.16807012183579
             */
            tle_line2: string;
            /**
             * Satellite Name
             * @default SIM-OPTICAL-01
             */
            satellite_name: string;
            /**
             * Ground Station Name
             * @default GS-DEMO-BEIJING
             */
            ground_station_name: string;
            /**
             * Ground Station Latitude
             * @default 39.9042
             */
            ground_station_latitude: number;
            /**
             * Ground Station Longitude
             * @default 116.4074
             */
            ground_station_longitude: number;
            /**
             * Ground Station Altitude M
             * @default 50
             */
            ground_station_altitude_m: number;
            /**
             * Deterministic Contact
             * @default true
             */
            deterministic_contact: boolean;
            /**
             * Scene Id
             * @default demo-optical-scene
             */
            scene_id: string;
            /**
             * Scene Ready
             * @default true
             */
            scene_ready: boolean;
            /** Links */
            links?: {
                [key: string]: components["schemas"]["LinkProfile"];
            };
            sensor?: components["schemas"]["SensorSettings"];
        };
        /** ScenarioControl */
        ScenarioControl: {
            action: components["schemas"]["ClockAction"];
            /** Rate */
            rate?: (1 | 10 | 100) | null;
            /**
             * Step Seconds
             * @default 1
             */
            step_seconds: number;
        };
        /**
         * SensorSettings
         * @description Validated optical-sensor parameters frozen with a scenario.
         */
        SensorSettings: {
            /**
             * Bit Depth
             * @default 12
             */
            bit_depth: number;
            /**
             * Gain
             * @default 1
             */
            gain: number;
            /**
             * Offset Dn
             * @default 32
             */
            offset_dn: number;
            /**
             * Dark Current Dn
             * @default 4
             */
            dark_current_dn: number;
            /**
             * Read Noise Dn
             * @default 0
             */
            read_noise_dn: number;
            /**
             * Prnu Sigma
             * @default 0
             */
            prnu_sigma: number;
            /**
             * Bad Pixel Rate
             * @default 0
             */
            bad_pixel_rate: number;
            /**
             * Stripe Amplitude Dn
             * @default 0
             */
            stripe_amplitude_dn: number;
            /**
             * Line Period Ms
             * @default 1
             */
            line_period_ms: number;
        };
        /** TelemetryEvent */
        TelemetryEvent: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Mission Id */
            mission_id?: string | null;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
            /** Event Type */
            event_type: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /**
             * Simulated At
             * Format: date-time
             */
            simulated_at: string;
            /** Source */
            source: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Provenance
             * @default simulated
             * @enum {string}
             */
            provenance: "measured" | "derived" | "simulated" | "placeholder";
            /**
             * Channel
             * @default simulation_control
             * @enum {string}
             */
            channel: "simulation_control" | "uplink" | "gtx" | "downlink";
        };
        /** TransferRecord */
        TransferRecord: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Mission Id */
            mission_id: string;
            link: components["schemas"]["LinkKind"];
            /** Name */
            name: string;
            /** Total Bytes */
            total_bytes: number;
            /**
             * Transferred Bytes
             * @default 0
             */
            transferred_bytes: number;
            /**
             * Frame Count
             * @default 0
             */
            frame_count: number;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Crc Failures
             * @default 0
             */
            crc_failures: number;
            /** Sha256 */
            sha256: string;
            /** @default queued */
            status: components["schemas"]["TransferStatus"];
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Protocol Transaction Id */
            protocol_transaction_id?: string | null;
        };
        /**
         * TransferStatus
         * @enum {string}
         */
        TransferStatus: "queued" | "transferring" | "retrying" | "completed" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    public_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    provider_health_api_providers_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    import_scene_api_scenes_import_post: {
        parameters: {
            query: {
                scene_id: string;
                scenario_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_scene_api_scenes_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_scenario_yaml_api_scenarios_import_yaml_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_scenario_yaml_api_scenarios_import_yaml_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_orbit_api_scenarios__scenario_id__orbit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_scenario_api_scenarios__scenario_id__control_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioControl"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missions_api_missions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionSummary"][];
                };
            };
        };
    };
    create_mission_api_missions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_mission_api_missions__mission_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionAdvance"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mission_api_missions__mission_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_api_missions__mission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_snapshot_api_missions__mission_id__nodes__node__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
                node: components["schemas"]["NodeKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_artifact_api_missions__mission_id__nodes__node__artifacts__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
                node: components["schemas"]["NodeKind"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_result_api_missions__mission_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_faults_api_scenarios__scenario_id__faults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultRule"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_fault_api_scenarios__scenario_id__faults_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultRule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fault_api_scenarios__scenario_id__faults__fault_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
                fault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transfers_api_transfers_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_protocol_transactions_api_missions__mission_id__protocol_transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolTransaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_protocol_transaction_api_protocol_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolTransaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_protocol_frames_api_protocol_transactions__transaction_id__frames_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolFrameTrace"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_protocol_api_protocol_stream_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_manifest_api_products__product_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_stream_get: {
        parameters: {
            query: {
                run_id: string;
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
